% UPDATE  Update Simulink's Polynomial Library block.
%
% This macro is intended to be called only by the Polynomial Library
% blocks' masks.
%
% See also POLYNOMIAL LIBRARY (in SIMULINK), POLYMASK. 

%	Author(s): M. Hromcik, M. Sebek 7-9-98
%	Copyright (c) 1998 by Polyx, Ltd.
%       $Revision: 2.0 $  $Date: 7-Sep-1998 10:28:34   $

Block = gcb;

ss = find_system(Block,'LookUnderMasks', 'on', 'name','Inner');

if isempty(ss),
  return
end;

if strcmp(get_param(ss{:},'blocktype'), 'DiscreteStateSpace') & ...
   ( strcmp(var, '(s)') | strcmp(var, '(p)') | strcmp(var, '') ),
   	
	replace_block(Block,'DiscreteStateSpace','StateSpace','noprompt');
	set_param([Block,'/Inner'], ...
           'A'          ,'A' , ...
           'B'          ,'B' , ...
           'C'          ,'C' , ...
           'D'          ,'D' , ...
           'X0'         ,'InCon'  ...
           );
           
elseif strcmp(get_param(ss{:},'blocktype'), 'StateSpace') & ...
       ~( strcmp(var, '(s)') | strcmp(var, '(p)') | strcmp(var, '') ),          
 
	replace_block(Block,'StateSpace','DiscreteStateSpace','noprompt');
	set_param([Block '/Inner'], ...
           'A'            ,'A' , ...
           'B'            ,'B' , ...
           'C'            ,'C' , ...
           'D'            ,'D' , ...
           'X0'           ,'InCon', ...
           'Sample time',  'SampTime'  ...
           );

end;            
           
